Pin setup-emacs@v6.0
- This fixes the error in Cache - Put:
    error: path '/home/runner/.nix-profile/bin/emacs-29.1' is not in the Nix store
- If we ever upgrade to a version with the changes currently on master, we may need
  to refresh the shell with a command like '. $HOME/.nix-profile/etc/profile.d/nix.sh'
  (or whatever path contains the profile script when installed for root)